spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/CivicHelpDB
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: matar

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
